version: "3.9"

services:
  user-notifications-manager:
    container_name: user-notifications-manager
    build: 
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - PORT=8080
      - REDIS_QUEUE_NAME=notifications-queue
      - REDIS_URL=redis://redis:6379
      - BG_NOTIFICATIONS_SENDER_INTERVAL=1000
      - NOTIFICATION_SERVICE_URL=http://notification-service:5001
      - WINDOW_TIMEOUT=20000
      - WINDOW_COUNT=5
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - notification-service
    networks:
      - vim

  notification-service:
    image: aryekog/backend-interview-notifications-service:0.0.2
    ports:
      - "5001:5001"
    environment:
      - EMAIL_RATE_LIMIT=1
      - SMS_RATE_LIMIT=1
      - RATE_LIMIT_WINDOW_MS=1000
      - ERROR_RATE=0.1 
    networks:
      - vim

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - vim

networks:
  vim:
    driver: bridge

volumes:
  data:
    driver: local
