version: "3.9"

services:
  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
    networks:
      - backend
  notification-service:
    image: aryekog/backend-interview-notifications-service:0.0.2
    ports:
      - "5001:5001"
    environment:
      - EMAIL_RATE_LIMIT=1
      - SMS_RATE_LIMIT=1
      - RATE_LIMIT_WINDOW_MS=1000
      - ERROR_RATE=0.1 
    networks:
      - backend
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
